### ISSUE TITLE
Sync Token not found

### ISSUE THREAD

**Issue by olegIvani4** [phoboslab/jsmpeg#115]
Hello @phoboslab,

I've found that `jsmpeg` is not working in Safari iOS9 [9.3.2].
I have a lot of errors like
```
Sync Token not found
``` 
and 
```
TypeError: this.blockData.fill is not a function. (In 'this.blockData.fill(0)', 'this.blockData.fill' is undefined)
```
and
```
TypeError: this.imageData.data.fill is not a function. (In 'this.imageData.data.fill(255)', 'this.imageData.data.fill' is undefined)
```

Same stream works in Safari iOS10 and also on desktop. 
My `ffmpeg` command: 
```
$ ffmpeg -rtsp_transport tcp -i rtsp://camera.ip:port/secret -f mpegts -codec:v mpeg1video -s 1280x720 -b:v 1000k -bf 0 http://localhost:8081/supersecret
``` 
And client configuration: 
```
var player = new JSMpeg.Player(url, {
    canvas: canvas,
    disableGl: true,
    loop: false,
    autoplay: true,
    audio: false,
    videoBufferSize: 1280*720,
});
```
I've tried with enabled WebGL too, doesn't help.

**Comment by phoboslab** [comment]
Well, it seems that `.fill()` is not implemented for Typed Arrays in iOS9.

The [Polyfill suggested on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill) is pretty simple, though. Can you give it a try? I don't have any iOS9 to test this on.

If this is the only problem on iOS9, I'll add the Polyfill.

**Comment by olegIvani4** [comment]
yes, adding Polyfills solved errors
```
if (!Array.prototype.fill) {
  Object.defineProperty(Array.prototype, 'fill', {
    value: function(value) {

      // Steps 1-2.
      if (this == null) {
        throw new TypeError('this is null or not defined');
      }

      var O = Object(this);

      // Steps 3-5.
      var len = O.length >>> 0;

      // Steps 6-7.
      var start = arguments[1];
      var relativeStart = start >> 0;

      // Step 8.
      var k = relativeStart < 0 ?
        Math.max(len + relativeStart, 0) :
        Math.min(relativeStart, len);

      // Steps 9-10.
      var end = arguments[2];
      var relativeEnd = end === undefined ?
        len : end >> 0;

      // Step 11.
      var final = relativeEnd < 0 ?
        Math.max(len + relativeEnd, 0) :
        Math.min(relativeEnd, len);

      // Step 12.
      while (k < final) {
        O[k] = value;
        k++;
      }

      // Step 13.
      return O;
    }
  });
}
if (!Uint8Array.prototype.fill) {
  Uint8Array.prototype.fill = Array.prototype.fill;
}
if (!Uint8ClampedArray.prototype.fill) {
  Uint8ClampedArray.prototype.fill = Array.prototype.fill;
}
if (!Int32Array.prototype.fill) {
  Int32Array.prototype.fill = Array.prototype.fill;
}
```

But performance is dramatic. I have iOS9 on iPhone 4S, and I get 0-1 FPS, no mater if WebGL is enabled or not.

**Comment by olegIvani4** [comment]
on same device but in Chrome I got 7-11 FPS.

**Comment by olegIvani4** [comment]
Tomorrow will try smaller resolution

**Comment by phoboslab** [comment]
Chrome on iOS uses a WKWebView - essentially Safari without the Safari UI. It's not allowed to use anything else. So, running the video directly in Safari should give you the same result.

Note that some Apps still use the older **UI**WebView to display websites, which is not allowed to use the JavaScript JIT. So I assume when you got the 0-1 FPS, you were testing in a Phonegap App or something similar!?

**Comment by olegIvani4** [comment]
No, I was testing in Safari you test page `view-stream.html` served via `http-server`

**Comment by phoboslab** [comment]
Added a workaround for `array.fill` in https://github.com/phoboslab/jsmpeg/commit/85588a30fedefe7a36ea5e59f57ea4c4c1b5aecc

I'll have a look at the performance issues on iOS9 on monday.
